# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: pwd
        run: pwd
      
      - name: ls -a
        run: ls -a
      
      - name: tree
        run: tree
      
      - name: Setup Processing
        uses: ifP1/setup-processing@v1.1.1
        with:
          # Version of Processing, e.g. 3.5.4
          version: 3.5.4 # default is 3.5.4
          # e.g. 'windows64.zip', 'windows32.zip', 'linux64.tgz'
          platform-filetype: linux64.tgz # optional, default is linux64.tgz
      
      # https://github.com/processing/processing/wiki/Command-Line
      - name: Build with Processing
        run: processing-java --sketch=/home/runner/work/SolarSystem/SolarSystem --output=/home/runner/work/SolarSystem/SolarSystem/artifacts/build --build

      #- name: Export with Processing (to Linux)
      #  run: processing-java --sketch=/home/runner/work/SolarSystem/SolarSystem --output=/home/runner/work/SolarSystem/SolarSystem/artifacts/export/linux --export --platform=linux
        
      #- name: Export with Processing (to Windows)
      #  run: processing-java --sketch=/home/runner/work/SolarSystem/SolarSystem --output=/home/runner/work/SolarSystem/SolarSystem/artifacts/export/windows --export --platform=windows
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: /home/runner/work/SolarSystem/SolarSystem/artifacts/
